name: Test checkout

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    container: ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: iterative/setup-cml@v1
      - name: dump refs
        run: |
          cml ci
          cat .git/config
          echo "git branch -l"
          git --no-pager branch -l
          echo "git diff origin/main origin/some-branch"
          git --no-pager diff origin/main origin/some-branch
          echo "git diff refs/remotes/origin/main refs/remotes/origin/some-branch"
          git --no-pager diff refs/remotes/origin/main refs/remotes/origin/some-branch
          echo "tree .git/refs"
          tree .git/refs
